src/assets/Main/mainCard_NameRecognition_img.svg
=> 2022-05-23 개체명 인식 카드 이미지 변경

README.md, public/index.html, public/manifest.json
- 기존 HyperBrain으로 등록되어 있던 메타 정보를 SuperBrain으로 수정
=> 2022-05-23 메타 데이터 수정

src/components/header/header.jsx, src/pages/Home/Home.jsx, src/pages/STTDemo/index.jsx, src/pages/TTSDemo/index.jsx
=> 2022-05-24 In Page Drag Issue

src/pages/STTDemo/soundConvert/dropzone.jsx, src/pages/STTDemo/soundConvert/soundConvert.jsx
STT
-dropzone에 존재하는 hook을 soundConvert에 추가
기타 사항) dropzone 매개변수 추가
=> 2022-05-25

src/pages/VideoCaptionDemo/videoCaption/uploadZone.jsx
2022-05-25 영상 자막 생성 Discription 수정
기존 : 선택된 파일이 없습니다. 파일을 업로드 해주세요. 확장자는 mp4를 지원합니다.
수정 : 영상 파일을 마우스로 드래그하거나, 아이콘을 눌러 영상 파일을 업로드해주세요. 영상 파일 크기에 비례하여 시간이 걸립니다. (지원파일 : mp4, mkv, m4v)
=> Jaegeun kim/upload zone/description

src/pages/STTDemo/soundConvert/dropzone.jsx
=> Jaegeun kim/27

src/pages/TTSDemo/tts/tts.jsx
이전 : <TextLimitDiv>글자 수(공백포함) : {file.text.length} / 300</TextLimitDiv> 폰트 16px
수정 : <TextLimitDiv>글자 수(공백포함) : {file.text.length} / 200 (자음, 모음 또는 특수문자는 기입 불가)</TextLimitDiv> 폰트 13px
=> Issue Number #29 TTS 텍스트박스 하단 제한 글자 수 수정 및 안내문구 추가

src/pages/VideoCaptionDemo/videoCaption/videoCaption.jsx
2022-05-31 videoCaption.jsx 에서 업로드 전 "파일명 : " 노출 제거
이전 : {<span>파일명 : {file?.name}</span>}
수정 : {file ? (<span>파일명 : {file.name}</span>) : <></>}
=> videoCaption.jsx 에서 업로드 전 "파일명 : " 노출 제거

src/utils/txt.js
=> 2022-05-31 STT 텍스트 다운로드 Alert 수정

src/pages/TTSDemo/tts/tts.jsx
- 데모를 체험하기 문구로 수정
2022-05-31 complete
=> 2022-05-31 Modify Concept TTS Alert 문구 수정

src/pages/VideoCaptionDemo/index.jsx
=> 2022-05-31 #45 영상자막생성 텍스트 수정

src/pages/STTDemo/index.jsx
=> 2022-05-31 STT / 제품 소개 텍스트 수정

src/pages/VideoCaptionDemo/videoCaption/uploadZone.jsx, src/pages/VideoCaptionDemo/videoCaption/videoCaption.jsx
변환페이지 추가 및 추가된 페이지에 노출되는 파일명 생략 추가
=> Jaegeun kim/29

src/pages/VideoCaptionDemo/videoCaption/uploadZone.jsx
2022-06-07 videocaption uploadZone.jsx loading t시 파일명 생략
=> videocaption uploadZone.jsx loading 파일명 생략

src/pages/VideoCaptionDemo/videoCaption/videoCaption.jsx
2022-06-07 videocaption videoCaption.jsx header 파일명 생략 추가
=> videocaption videoCaption.jsx header 파일명 생략 추가

src/pages/STTDemo/soundConvert/dropzone.jsx
STT dropzone.jsx loading 시 파일명 생략 추가
=> STT dropzone.jsx loading 시 파일명 생략 추가

src/pages/STTDemo/soundConvert/soundConvert.jsx
STT soundConvert.jsx 헤더 파일명 생략 추가
=> STT soundConvert.jsx 헤더 파일명 생략 추가

src/pages/STTDemo/soundConvert/mediaPlayer/wordplayer.jsx
내부 스크롤 속성에 overscroll-behavior: contain; 추가
=> 2022-06-02 STT 내부 스크롤과 외부 스크롤 체인 현상 방지

src/pages/VideoCaptionDemo/videoCaption/videoCaption.jsx
=> videoCaption.jsx CaptionLayout 속성 overscroll-behavior : contain; 추가

src/components/footer/businessFooter.jsx, src/components/header/techHeader.jsx, src/pages/Home/Home.jsx
=> [Bug Fix] 제품소개서 버튼 활성화

src/pages/TTSDemo/tts/select.jsx, src/pages/TTSDemo/tts/setting.jsx, src/pages/TTSDemo/tts/tts.jsx
=> TTS 재생 중 옵션 비활성화

src/pages/STTDemo/soundConvert/mediaPlayer/mediaplayer.jsx
STT 재생 종료 시 isPlay false로 change 및 재생 중지
=> Issue Number 56 ) STT 재생 종료 시 isPlay false로 change 및 재생 중지

src/pages/TTSDemo/tts/tts.jsx
=> TTS 내용 없을 시 다운로드 버튼 Disable

src/pages/TTSDemo/tts/tts.jsx
TTS 내용 없을 시 재생 버튼 disable 및 cursor default
=> TTS 내용 없을 시 재생 버튼 disable 및 cursor default

src/pages/VideoCaptionDemo/videoCaption/videoCaption.jsx
2022-06-13 영상 Caption video width : 450 | height : 255 로 수정
=> 영상 Caption video width : 450 | height : 255 로 수정

src/pages/VideoCaptionDemo/videoCaption/captionsBox.jsx
=> Jaegeun kim/80
